apiVersion: v1
kind: Secret
metadata:
  namespace: mango
  name: crank
  labels:
    app: crank-market-service
    cluster: testnet
type: Opaque
data:
  # 2DMfHTL1GK7t9ARX5H6bg3pctBoPmYppg7uwzV2hg2d3
  SECRET_KEY: "WzIyMCwxMjQsMTM0LDIxMCwxODYsMjUzLDM5LDE5OCwyMTQsMTgsMTI5LDE4OCw1MCwxOTcsMjUzLDI2LDIyMSwxNTEsODAsMTU1LDE5Myw1MiwyMDEsNTQsNjEsNjgsMCwzNywxMzksMTIzLDgxLDE5OSwxOCw2LDQsOTIsMjQ4LDE3NCw4NSwxMjksMjMzLDE1OSwxNTUsMTE5LDE5NiwyMSwzLDE2NCw1Miw3LDI1Myw4Niw4OSwyMzIsMTY1LDE3Nyw1MywyMzUsMTA3LDI3LDE3OCw2LDg1LDZd"
